
var spineWasm = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(spineWasm = {})  {

var h;h||(h=typeof spineWasm !== 'undefined' ? spineWasm : {});var aa,ba;h.ready=new Promise((a,b)=>{aa=a;ba=b});var da=Object.assign({},h),q="";"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src);_scriptDir&&(q=_scriptDir);0!==q.indexOf("blob:")?q=q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):q="";var v=h.printErr||console.error.bind(console);Object.assign(h,da);da=null;var x;h.wasmBinary&&(x=h.wasmBinary);var noExitRuntime=h.noExitRuntime||!0;
"object"!=typeof WebAssembly&&z("no native wasm support detected");var ea,fa=!1,ha,A,B,ia,C,D,ja,ka;function la(){var a=ea.buffer;h.HEAP8=ha=new Int8Array(a);h.HEAP16=B=new Int16Array(a);h.HEAP32=C=new Int32Array(a);h.HEAPU8=A=new Uint8Array(a);h.HEAPU16=ia=new Uint16Array(a);h.HEAPU32=D=new Uint32Array(a);h.HEAPF32=ja=new Float32Array(a);h.HEAPF64=ka=new Float64Array(a)}var ma,na=[],oa=[],pa=[];function qa(){var a=h.preRun.shift();na.unshift(a)}var E=0,ra=null,F=null;
function z(a){if(h.onAbort)h.onAbort(a);a="Aborted("+a+")";v(a);fa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}function sa(a){return a.startsWith("data:application/octet-stream;base64,")}var G;G="spine.wasm";if(!sa(G)){var ta=G;G=h.locateFile?h.locateFile(ta,q):q+ta}function ua(a){try{if(a==G&&x)return new Uint8Array(x);throw"both async and sync fetching of the wasm failed";}catch(b){z(b)}}
function va(a){return x||"function"!=typeof fetch?Promise.resolve().then(()=>ua(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>ua(a))}function wa(a,b,c){return va(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{v("failed to asynchronously prepare wasm: "+d);z(d)})}
function xa(a,b){var c=G;return x||"function"!=typeof WebAssembly.instantiateStreaming||sa(c)||"function"!=typeof fetch?wa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){v("wasm streaming compile failed: "+e);v("falling back to ArrayBuffer instantiation");return wa(c,a,b)}))}var za={22280:a=>{console.warn("[Spine]",a?ya(a):"")}};function Aa(a){for(;0<a.length;)a.shift()(h)}
function Ba(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError(`Unknown type size: ${a}`);}}var Ca=void 0;function I(a){for(var b="";A[a];)b+=Ca[A[a++]];return b}var J={},K={},Da={};function Ea(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a}function Fa(a,b){a=Ea(a);return{[a]:function(){return b.apply(this,arguments)}}[a]}
function Ga(a){var b=Error,c=Fa(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c}var L=void 0;function M(a){throw new L(a);}var Ha=void 0;function Ia(a){throw new Ha(a);}
function O(a,b,c){function d(f){f=c(f);f.length!==a.length&&Ia("Mismatched type converter count");for(var l=0;l<a.length;++l)P(a[l],f[l])}a.forEach(function(f){Da[f]=b});var e=Array(b.length),g=[],k=0;b.forEach((f,l)=>{K.hasOwnProperty(f)?e[l]=K[f]:(g.push(f),J.hasOwnProperty(f)||(J[f]=[]),J[f].push(()=>{e[l]=K[f];++k;k===g.length&&d(e)}))});0===g.length&&d(e)}
function P(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||M(`type "${d}" must have a positive integer typeid pointer`);if(K.hasOwnProperty(a)){if(c.ma)return;M(`Cannot register type '${d}' twice`)}K[a]=b;delete Da[a];J.hasOwnProperty(a)&&(b=J[a],delete J[a],b.forEach(e=>e()))}function Ja(a){M(a.H.K.I.name+" instance already deleted")}var Ka=!1;function La(){}
function Ma(a){--a.count.value;0===a.count.value&&(a.N?a.O.U(a.N):a.K.I.U(a.J))}function Na(a,b,c){if(b===c)return a;if(void 0===c.L)return null;a=Na(a,b,c.L);return null===a?null:c.ja(a)}var Oa={},Q=[];function Pa(){for(;Q.length;){var a=Q.pop();a.H.W=!1;a["delete"]()}}var R=void 0,S={};function Qa(a,b){for(void 0===b&&M("ptr should not be undefined");a.L;)b=a.Y(b),a=a.L;return S[b]}
function Ra(a,b){b.K&&b.J||Ia("makeClassHandle requires ptr and ptrType");!!b.O!==!!b.N&&Ia("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Sa(Object.create(a,{H:{value:b}}))}function Sa(a){if("undefined"===typeof FinalizationRegistry)return Sa=b=>b,a;Ka=new FinalizationRegistry(b=>{Ma(b.H)});Sa=b=>{var c=b.H;c.N&&Ka.register(b,{H:c},b);return b};La=b=>{Ka.unregister(b)};return Sa(a)}function T(){}
function Ta(a,b,c){if(void 0===a[b].M){var d=a[b];a[b]=function(){a[b].M.hasOwnProperty(arguments.length)||M(`Function '${c}' called with an invalid number of arguments (${arguments.length}) - expects one of (${a[b].M})!`);return a[b].M[arguments.length].apply(this,arguments)};a[b].M=[];a[b].M[d.V]=d}}
function Ua(a,b){h.hasOwnProperty(a)?(M(`Cannot register public name '${a}' twice`),Ta(h,a,a),h.hasOwnProperty(void 0)&&M("Cannot register multiple overloads of a function with the same number of arguments (undefined)!"),h[a].M[void 0]=b):h[a]=b}function Va(a,b,c,d,e,g,k,f){this.name=a;this.constructor=b;this.S=c;this.U=d;this.L=e;this.ka=g;this.Y=k;this.ja=f;this.oa=[]}
function Wa(a,b,c){for(;b!==c;)b.Y||M(`Expected null or instance of ${c.name}, got an instance of ${b.name}`),a=b.Y(a),b=b.L;return a}function Xa(a,b){if(null===b)return this.ba&&M(`null is not a valid ${this.name}`),0;b.H||M(`Cannot pass "${Ya(b)}" as a ${this.name}`);b.H.J||M(`Cannot pass deleted object as a pointer of type ${this.name}`);return Wa(b.H.J,b.H.K.I,this.I)}
function Za(a,b){if(null===b){this.ba&&M(`null is not a valid ${this.name}`);if(this.aa){var c=this.pa();null!==a&&a.push(this.U,c);return c}return 0}b.H||M(`Cannot pass "${Ya(b)}" as a ${this.name}`);b.H.J||M(`Cannot pass deleted object as a pointer of type ${this.name}`);!this.$&&b.H.K.$&&M(`Cannot convert argument of type ${b.H.O?b.H.O.name:b.H.K.name} to parameter type ${this.name}`);c=Wa(b.H.J,b.H.K.I,this.I);if(this.aa)switch(void 0===b.H.N&&M("Passing raw pointer to smart pointer is illegal"),
this.sa){case 0:b.H.O===this?c=b.H.N:M(`Cannot convert argument of type ${b.H.O?b.H.O.name:b.H.K.name} to parameter type ${this.name}`);break;case 1:c=b.H.N;break;case 2:if(b.H.O===this)c=b.H.N;else{var d=b.clone();c=this.qa(c,U(function(){d["delete"]()}));null!==a&&a.push(this.U,c)}break;default:M("Unsupporting sharing policy")}return c}
function $a(a,b){if(null===b)return this.ba&&M(`null is not a valid ${this.name}`),0;b.H||M(`Cannot pass "${Ya(b)}" as a ${this.name}`);b.H.J||M(`Cannot pass deleted object as a pointer of type ${this.name}`);b.H.K.$&&M(`Cannot convert argument of type ${b.H.K.name} to parameter type ${this.name}`);return Wa(b.H.J,b.H.K.I,this.I)}function ab(a){return this.fromWireType(C[a>>2])}
function V(a,b,c,d){this.name=a;this.I=b;this.ba=c;this.$=d;this.aa=!1;this.U=this.qa=this.pa=this.fa=this.sa=this.na=void 0;void 0!==b.L?this.toWireType=Za:(this.toWireType=d?Xa:$a,this.R=null)}function bb(a,b){h.hasOwnProperty(a)||Ia("Replacing nonexistant public symbol");h[a]=b;h[a].V=void 0}
function cb(a,b){var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=h["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=ma.get(b).apply(null,c);return d}}function W(a,b){a=I(a);var c=a.includes("j")?cb(a,b):ma.get(b);"function"!=typeof c&&M(`unknown function pointer with signature ${a}: ${b}`);return c}var db=void 0;function eb(a){a=fb(a);var b=I(a);X(a);return b}
function Y(a,b){function c(g){e[g]||K[g]||(Da[g]?Da[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new db(`${a}: `+d.map(eb).join([", "]));}function gb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function hb(a,b,c,d,e){var g=b.length;2>g&&M("argTypes array size mismatch! Must at least get return value and 'this' types!");var k=null!==b[1]&&null!==c,f=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].R){f=!0;break}var l="void"!==b[0].name,n=g-2,m=Array(n),p=[],r=[];return function(){arguments.length!==n&&M(`function ${a} called with ${arguments.length} arguments, expected ${n} args!`);r.length=0;p.length=k?2:1;p[0]=e;if(k){var u=b[1].toWireType(r,this);p[1]=u}for(var t=0;t<n;++t)m[t]=
b[t+2].toWireType(r,arguments[t]),p.push(m[t]);t=d.apply(null,p);if(f)gb(r);else for(var w=k?1:2;w<b.length;w++){var H=1===w?u:m[w-2];null!==b[w].R&&b[w].R(H)}u=l?b[0].fromWireType(t):void 0;return u}}function ib(a,b){for(var c=[],d=0;d<a;d++)c.push(D[b+4*d>>2]);return c}
function jb(a,b,c){a instanceof Object||M(`${c} with invalid "this": ${a}`);a instanceof b.I.constructor||M(`${c} incompatible with "this" of type ${a.constructor.name}`);a.H.J||M(`cannot call emscripten binding method ${c} on deleted object`);return Wa(a.H.J,a.H.K.I,b.I)}
var Z=new function(){this.P=[void 0];this.ca=[];this.get=function(a){return this.P[a]};this.has=function(a){return void 0!==this.P[a]};this.ga=function(a){var b=this.ca.pop()||this.P.length;this.P[b]=a;return b};this.ha=function(a){this.P[a]=void 0;this.ca.push(a)}};function lb(a){a>=Z.da&&0===--Z.get(a).ra&&Z.ha(a)}
var mb=a=>{a||M("Cannot use deleted val. handle = "+a);return Z.get(a).value},U=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:return Z.ga({ra:1,value:a})}};function Ya(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function nb(a,b){switch(b){case 2:return function(c){return this.fromWireType(ja[c>>2])};case 3:return function(c){return this.fromWireType(ka[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function ob(a,b,c){switch(b){case 0:return c?function(d){return ha[d]}:function(d){return A[d]};case 1:return c?function(d){return B[d>>1]}:function(d){return ia[d>>1]};case 2:return c?function(d){return C[d>>2]}:function(d){return D[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var pb="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ya(a,b){var c=A,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&pb)return pb.decode(c.subarray(a,b));for(d="";a<b;){var e=c[a++];if(e&128){var g=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var k=c[a++]&63;e=224==(e&240)?(e&15)<<12|g<<6|k:(e&7)<<18|g<<12|k<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
var qb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function rb(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&ia[c];)++c;c<<=1;if(32<c-a&&qb)return qb.decode(A.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=B[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}function sb(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)B[b>>1]=a.charCodeAt(e),b+=2;B[b>>1]=0;return b-d}function tb(a){return 2*a.length}
function ub(a,b){for(var c=0,d="";!(c>=b/4);){var e=C[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}function vb(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var k=a.charCodeAt(++e);g=65536+((g&1023)<<10)|k&1023}C[b>>2]=g;b+=4;if(b+4>c)break}C[b>>2]=0;return b-d}
function wb(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function xb(a,b){var c=K[a];void 0===c&&M(b+" has unknown type "+eb(a));return c}var yb={},zb=[];function Ab(){var a=h.SpineWasmUtil,b=a.getCurrentListenerID(),c=a.getCurrentTrackEntry(),d=a.getCurrentEvent();a=a.getCurrentEventType();globalThis.TrackEntryListeners.emitListener(b,c,d,a)}h._spineListenerCallBackFromJS=Ab;
function Bb(){var a=h.SpineWasmUtil,b=a.getCurrentListenerID(),c=a.getCurrentEventType(),d=a.getCurrentTrackEntry();a=a.getCurrentEvent();globalThis.TrackEntryListeners.emitTrackEntryListener(b,d,a,c)}h._spineTrackListenerCallback=Bb;for(var Cb=Array(256),Db=0;256>Db;++Db)Cb[Db]=String.fromCharCode(Db);Ca=Cb;L=h.BindingError=Ga("BindingError");Ha=h.InternalError=Ga("InternalError");
T.prototype.isAliasOf=function(a){if(!(this instanceof T&&a instanceof T))return!1;var b=this.H.K.I,c=this.H.J,d=a.H.K.I;for(a=a.H.J;b.L;)c=b.Y(c),b=b.L;for(;d.L;)a=d.Y(a),d=d.L;return b===d&&c===a};T.prototype.clone=function(){this.H.J||Ja(this);if(this.H.X)return this.H.count.value+=1,this;var a=Sa,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.H;a=a(c.call(b,d,{H:{value:{count:e.count,W:e.W,X:e.X,J:e.J,K:e.K,N:e.N,O:e.O}}}));a.H.count.value+=1;a.H.W=!1;return a};
T.prototype["delete"]=function(){this.H.J||Ja(this);this.H.W&&!this.H.X&&M("Object already scheduled for deletion");La(this);Ma(this.H);this.H.X||(this.H.N=void 0,this.H.J=void 0)};T.prototype.isDeleted=function(){return!this.H.J};T.prototype.deleteLater=function(){this.H.J||Ja(this);this.H.W&&!this.H.X&&M("Object already scheduled for deletion");Q.push(this);1===Q.length&&R&&R(Pa);this.H.W=!0;return this};h.getInheritedInstanceCount=function(){return Object.keys(S).length};
h.getLiveInheritedInstances=function(){var a=[],b;for(b in S)S.hasOwnProperty(b)&&a.push(S[b]);return a};h.flushPendingDeletes=Pa;h.setDelayFunction=function(a){R=a;Q.length&&R&&R(Pa)};V.prototype.la=function(a){this.fa&&(a=this.fa(a));return a};V.prototype.ea=function(a){this.U&&this.U(a)};V.prototype.argPackAdvance=8;V.prototype.readValueFromPointer=ab;V.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
V.prototype.fromWireType=function(a){function b(){return this.aa?Ra(this.I.S,{K:this.na,J:c,O:this,N:a}):Ra(this.I.S,{K:this,J:a})}var c=this.la(a);if(!c)return this.ea(a),null;var d=Qa(this.I,c);if(void 0!==d){if(0===d.H.count.value)return d.H.J=c,d.H.N=a,d.clone();d=d.clone();this.ea(a);return d}d=this.I.ka(c);d=Oa[d];if(!d)return b.call(this);d=this.$?d.ia:d.pointerType;var e=Na(c,this.I,d.I);return null===e?b.call(this):this.aa?Ra(d.I.S,{K:d,J:e,O:this,N:a}):Ra(d.I.S,{K:d,J:e})};
db=h.UnboundTypeError=Ga("UnboundTypeError");Z.P.push({value:void 0},{value:null},{value:!0},{value:!1});Z.da=Z.P.length;h.count_emval_handles=function(){for(var a=0,b=Z.da;b<Z.P.length;++b)void 0!==Z.P[b]&&++a;return a};
var Fb={t:function(){},w:function(a,b,c,d,e){var g=Ba(c);b=I(b);P(a,{name:b,fromWireType:function(k){return!!k},toWireType:function(k,f){return f?d:e},argPackAdvance:8,readValueFromPointer:function(k){if(1===c)var f=ha;else if(2===c)f=B;else if(4===c)f=C;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(f[k>>g])},R:null})},c:function(a,b,c,d,e,g,k,f,l,n,m,p,r){m=I(m);g=W(e,g);f&&(f=W(k,f));n&&(n=W(l,n));r=W(p,r);var u=Ea(m);Ua(u,function(){Y(`Cannot construct ${m} due to unbound types`,
[d])});O([a,b,c],d?[d]:[],function(t){t=t[0];if(d){var w=t.I;var H=w.S}else H=T.prototype;t=Fa(u,function(){if(Object.getPrototypeOf(this)!==N)throw new L("Use 'new' to construct "+m);if(void 0===y.T)throw new L(m+" has no accessible constructor");var kb=y.T[arguments.length];if(void 0===kb)throw new L(`Tried to invoke ctor of ${m} with invalid number of parameters (${arguments.length}) - expected (${Object.keys(y.T).toString()}) parameters instead!`);return kb.apply(this,arguments)});var N=Object.create(H,
{constructor:{value:t}});t.prototype=N;var y=new Va(m,t,N,r,w,g,f,n);y.L&&(void 0===y.L.Z&&(y.L.Z=[]),y.L.Z.push(y));w=new V(m,y,!0,!1);H=new V(m+"*",y,!1,!1);var ca=new V(m+" const*",y,!1,!0);Oa[a]={pointerType:H,ia:ca};bb(u,t);return[w,H,ca]})},h:function(a,b,c,d,e,g,k){var f=ib(c,d);b=I(b);g=W(e,g);O([],[a],function(l){function n(){Y(`Cannot call ${m} due to unbound types`,f)}l=l[0];var m=`${l.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var p=l.I.constructor;void 0===p[b]?(n.V=c-
1,p[b]=n):(Ta(p,b,m),p[b].M[c-1]=n);O([],f,function(r){r=hb(m,[r[0],null].concat(r.slice(1)),null,g,k);void 0===p[b].M?(r.V=c-1,p[b]=r):p[b].M[c-1]=r;if(l.I.Z)for(const u of l.I.Z)u.constructor.hasOwnProperty(b)||(u.constructor[b]=r);return[]});return[]})},i:function(a,b,c,d,e,g,k,f){b=I(b);g=W(e,g);O([],[a],function(l){l=l[0];var n=`${l.name}.${b}`,m={get:function(){Y(`Cannot access ${n} due to unbound types`,[c])},enumerable:!0,configurable:!0};m.set=f?()=>{Y(`Cannot access ${n} due to unbound types`,
[c])}:()=>{M(`${n} is a read-only property`)};Object.defineProperty(l.I.constructor,b,m);O([],[c],function(p){p=p[0];var r={get:function(){return p.fromWireType(g(d))},enumerable:!0};f&&(f=W(k,f),r.set=u=>{var t=[];f(d,p.toWireType(t,u));gb(t)});Object.defineProperty(l.I.constructor,b,r);return[]});return[]})},d:function(a,b,c,d,e,g){0<b||z();var k=ib(b,c);e=W(d,e);O([],[a],function(f){f=f[0];var l=`constructor ${f.name}`;void 0===f.I.T&&(f.I.T=[]);if(void 0!==f.I.T[b-1])throw new L(`Cannot register multiple constructors with identical number of parameters (${b-
1}) for class '${f.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);f.I.T[b-1]=()=>{Y(`Cannot construct ${f.name} due to unbound types`,k)};O([],k,function(n){n.splice(1,0,null);f.I.T[b-1]=hb(l,n,null,e,g);return[]});return[]})},a:function(a,b,c,d,e,g,k,f){var l=ib(c,d);b=I(b);g=W(e,g);O([],[a],function(n){function m(){Y(`Cannot call ${p} due to unbound types`,l)}n=n[0];var p=`${n.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);
f&&n.I.oa.push(b);var r=n.I.S,u=r[b];void 0===u||void 0===u.M&&u.className!==n.name&&u.V===c-2?(m.V=c-2,m.className=n.name,r[b]=m):(Ta(r,b,p),r[b].M[c-2]=m);O([],l,function(t){t=hb(p,t,n,g,k);void 0===r[b].M?(t.V=c-2,r[b]=t):r[b].M[c-2]=t;return[]});return[]})},b:function(a,b,c,d,e,g,k,f,l,n){b=I(b);e=W(d,e);O([],[a],function(m){m=m[0];var p=`${m.name}.${b}`,r={get:function(){Y(`Cannot access ${p} due to unbound types`,[c,k])},enumerable:!0,configurable:!0};r.set=l?()=>{Y(`Cannot access ${p} due to unbound types`,
[c,k])}:()=>{M(p+" is a read-only property")};Object.defineProperty(m.I.S,b,r);O([],l?[c,k]:[c],function(u){var t=u[0],w={get:function(){var N=jb(this,m,p+" getter");return t.fromWireType(e(g,N))},enumerable:!0};if(l){l=W(f,l);var H=u[1];w.set=function(N){var y=jb(this,m,p+" setter"),ca=[];l(n,y,H.toWireType(ca,N));gb(ca)}}Object.defineProperty(m.I.S,b,w);return[]});return[]})},v:function(a,b){b=I(b);P(a,{name:b,fromWireType:function(c){var d=mb(c);lb(c);return d},toWireType:function(c,d){return U(d)},
argPackAdvance:8,readValueFromPointer:ab,R:null})},r:function(a,b,c){c=Ba(c);b=I(b);P(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){return e},argPackAdvance:8,readValueFromPointer:nb(b,c),R:null})},f:function(a,b,c,d,e){b=I(b);-1===e&&(e=4294967295);e=Ba(c);var g=f=>f;if(0===d){var k=32-8*c;g=f=>f<<k>>>k}c=b.includes("unsigned")?function(f,l){return l>>>0}:function(f,l){return l};P(a,{name:b,fromWireType:g,toWireType:c,argPackAdvance:8,readValueFromPointer:ob(b,e,0!==d),R:null})},
g:function(a,b,c){function d(g){g>>=2;var k=D;return new e(k.buffer,k[g+1],k[g])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=I(c);P(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{ma:!0})},p:function(a,b){b=I(b);var c="std::string"===b;P(a,{name:b,fromWireType:function(d){var e=D[d>>2],g=d+4;if(c)for(var k=g,f=0;f<=e;++f){var l=g+f;if(f==e||0==A[l]){k=k?ya(k,l-k):"";if(void 0===n)var n=k;else n+=String.fromCharCode(0),
n+=k;k=l+1}}else{n=Array(e);for(f=0;f<e;++f)n[f]=String.fromCharCode(A[g+f]);n=n.join("")}X(d);return n},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var g,k="string"==typeof e;k||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||M("Cannot pass non-string to std::string");var f;if(c&&k)for(g=f=0;g<e.length;++g){var l=e.charCodeAt(g);127>=l?f++:2047>=l?f+=2:55296<=l&&57343>=l?(f+=4,++g):f+=3}else f=e.length;g=f;f=Eb(4+g+1);l=f+4;D[f>>2]=g;
if(c&&k){if(k=l,l=g+1,g=A,0<l){l=k+l-1;for(var n=0;n<e.length;++n){var m=e.charCodeAt(n);if(55296<=m&&57343>=m){var p=e.charCodeAt(++n);m=65536+((m&1023)<<10)|p&1023}if(127>=m){if(k>=l)break;g[k++]=m}else{if(2047>=m){if(k+1>=l)break;g[k++]=192|m>>6}else{if(65535>=m){if(k+2>=l)break;g[k++]=224|m>>12}else{if(k+3>=l)break;g[k++]=240|m>>18;g[k++]=128|m>>12&63}g[k++]=128|m>>6&63}g[k++]=128|m&63}}g[k]=0}}else if(k)for(k=0;k<g;++k)n=e.charCodeAt(k),255<n&&(X(l),M("String has UTF-16 code units that do not fit in 8 bits")),
A[l+k]=n;else for(k=0;k<g;++k)A[l+k]=e[k];null!==d&&d.push(X,f);return f},argPackAdvance:8,readValueFromPointer:ab,R:function(d){X(d)}})},n:function(a,b,c){c=I(c);if(2===b){var d=rb;var e=sb;var g=tb;var k=()=>ia;var f=1}else 4===b&&(d=ub,e=vb,g=wb,k=()=>D,f=2);P(a,{name:c,fromWireType:function(l){for(var n=D[l>>2],m=k(),p,r=l+4,u=0;u<=n;++u){var t=l+4+u*b;if(u==n||0==m[t>>f])r=d(r,t-r),void 0===p?p=r:(p+=String.fromCharCode(0),p+=r),r=t+b}X(l);return p},toWireType:function(l,n){"string"!=typeof n&&
M(`Cannot pass non-string to C++ string type ${c}`);var m=g(n),p=Eb(4+m+b);D[p>>2]=m>>f;e(n,p+4,m+b);null!==l&&l.push(X,p);return p},argPackAdvance:8,readValueFromPointer:ab,R:function(l){X(l)}})},x:function(a,b){b=I(b);P(a,{ta:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},k:function(a,b,c){a=mb(a);b=xb(b,"emval::as");var d=[],e=U(d);D[c>>2]=e;return b.toWireType(d,a)},e:lb,l:function(a,b){a=mb(a);b=mb(b);return U(a[b])},m:function(a){var b=yb[a];return U(void 0===
b?I(a):b)},j:function(a){var b=mb(a);gb(b);lb(a)},s:function(a,b){a=xb(a,"_emval_take_value");a=a.readValueFromPointer(b);return U(a)},q:function(){z("")},o:function(a,b,c){zb.length=0;var d;for(c>>=2;d=A[b++];)c+=105!=d&c,zb.push(105==d?C[c]:ka[c++>>1]),++c;return za[a].apply(null,zb)},u:function(a){var b=A.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=e.min.call(e,2147483648,d+(65536-d%65536)%65536)-ea.buffer.byteLength+
65535>>>16;try{ea.grow(e);la();var g=1;break a}catch(k){}g=void 0}if(g)return!0}return!1},z:Ab,y:Bb};
(function(){function a(c){c=c.exports;h.asm=c;ea=h.asm.A;la();ma=h.asm.C;oa.unshift(h.asm.B);E--;h.monitorRunDependencies&&h.monitorRunDependencies(E);if(0==E&&(null!==ra&&(clearInterval(ra),ra=null),F)){var d=F;F=null;d()}return c}var b={a:Fb};E++;h.monitorRunDependencies&&h.monitorRunDependencies(E);if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){v("Module.instantiateWasm callback failed with error: "+c),ba(c)}xa(b,function(c){a(c.instance)}).catch(ba);return{}})();
function Eb(){return(Eb=h.asm.D).apply(null,arguments)}function X(){return(X=h.asm.E).apply(null,arguments)}function fb(){return(fb=h.asm.F).apply(null,arguments)}h.__embind_initialize_bindings=function(){return(h.__embind_initialize_bindings=h.asm.G).apply(null,arguments)};var Gb;F=function Hb(){Gb||Ib();Gb||(F=Hb)};
function Ib(){function a(){if(!Gb&&(Gb=!0,h.calledRun=!0,!fa)){Aa(oa);aa(h);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var b=h.postRun.shift();pa.unshift(b)}Aa(pa)}}if(!(0<E)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)qa();Aa(na);0<E||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);a()},1)):a())}}
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();Ib();


  return spineWasm.ready
}

);
})();
export default spineWasm;