
# set friendly platform define
if(IOS)
    set(platform_name ios)
    set(platform_spec_path ios)
elseif(ANDROID)
    set(platform_name android)
    set(platform_spec_path android/${ANDROID_ABI})
elseif(WINDOWS)
    set(platform_name win32)
    set(platform_spec_path win32)
elseif(MACOSX)
    set(platform_name mac)
    set(platform_spec_path mac)
elseif(OPENHARMONY)
    set(platform_name ohos)
    set(platform_spec_path openharmony/${OHOS_ARCH})
elseif(OHOS)
    set(platform_name ohos)
    set(platform_spec_path ohos/${OHOS_ARCH})
elseif(EMSCRIPTEN)
    set(platform_name emscripten)
    set(platform_spec_path emscripten)
elseif(LINUX)
    set(platform_name linux)
    set(platform_spec_path linux)
endif()

set(platform_spec_path "${CMAKE_CURRENT_LIST_DIR}/../${platform_spec_path}")
